sudo: required
services:
  - docker

before_install:
  - docker build -t shay18184/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shay18184/react-test npm test -- --coverage

after_success:
  - docker build -t shayliboironsrc/multi-client ./client
  - docker build -t shayliboironsrc/multi-nginx ./nginx
  - docker build -t shayliboironsrc/multi-server ./server
  - docker build -t shayliboironsrc/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push shayliboironsrc/multi-client
  - docker push shayliboironsrc/multi-nginx
  - docker push shayliboironsrc/multi-server
  - docker push shayliboironsrc/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-307977250180
  bucket_path: multi-docker-path
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY